# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1284a63c0bc66a70a2d7e35ba29890854ed3f562c0c41dc2cca2ddcc9c419cb0cb04c23fa59ce665c687f64160da6916dfb354674d48777984101621537bebc

test:
  secret_key_base: d16ea04460a091f46c4d9c66ab72567376f8721101757ea655e14630115a68122df76f29181f186dd1df9a99f0e8bccec3b6f1f2af64ed5049310de9855d21e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
